### ISSUE TITLE
Clicking fullscreen button fires click event on button beneath

### ISSUE THREAD

**Issue by nroyall** [metafizzy/flickity-fullscreen#8]
Hi! Thanks for the fantastic carousel! :)

I'm using the fullscreen option, and noticed a small issue with the button. I'm not sure whether it's an issue with the fullscreen JS or not. 

When the fullscreen gallery is open, if you click on `.flickity-fullscreen-button-exit`, the fullscreen overlay closes and any button that's directly beneath the flickity button also receives a click event. So for example, I have a click event handler attached to a search button, placed directly beneath the flickity button, which triggers a click on the search button too. 

It seems like the fullscreen positioning changes before the click event is finished, and exposes the element beneath to the click. Is there any way to prevent this? 

![screen shot 2018-05-10 at 3 19 13 pm](https://user-images.githubusercontent.com/7875771/39897572-a161354a-5467-11e8-885f-36b77dd5766a.png)

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm having trouble reproducing it. Could you fork this demo to show this issue: https://codepen.io/desandro/pen/MGVROW

**Comment by desandro** [comment]
Thank you for clearing that up! I'll have a fix in the next release.

In the meantime, you can resolve this bug by adding this [duck punch](https://metafizzy.co/blog/duck-punching-prototype/)

```
var exitButton = flkty.exitFullscreenButton;
exitButton.off( 'tap', exitButton.onTap );
```

See demo https://codepen.io/desandro/live/MGVROW

What's happening here: Flickity uses another library [tap-listener](https://github.com/metafizzy/tap-listener) to listen for click-like events for touch devices. This was necessary back in 2015, when mobile browsers had a 300 ms delay for emulated click events. Shortly  after Flickity was released, browsers removed the delay and so tap-listener was not necessary any more (I now know).

So Flickity uses this tap event to hide the overlay. Then the emulated click event fires without the overlay, thus triggering the click event on any underlying element.

The fix is to remove the tap-listener tap event and use the click event, so the overlay is still present when that fires.

**Comment by nroyall** [comment]
Okay, great, that makes sense, thank you!

**Comment by desandro** [comment]
flickity-fullscreen v1.1.0 has been released. With this fixed added. Thanks again for reporting this issue 🌈🐻

**Comment by jkosonen** [comment]
I'm still having this issue with v 1.1.1, also same issue with the original flickity package.
